version: 2

project_name: up-ns-list

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: up-ns-list
    main: ./main.go
    binary: up-ns-list
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: up-ns-list
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - list.up-schema

checksum:
  name_template: 'checksums-list.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: uplang
    name: ns
  draft: false
  prerelease: auto
  mode: keep-existing
  name_template: "Namespace: list v{{.Version}}"

brews:
  - name: up-ns-list
    repository:
      owner: uplang
      name: brew
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/uplang/ns
    description: "UP namespace plugin for list generation and manipulation"
    license: GPL-3.0
    skip_upload: auto
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

